# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.12.0]
    steps:
      - name: 1. 检查master分支
        uses: actions/checkout@master

      - name: 2. 设置Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: 3. 安装插件
        run: npm install

      - name: 4. 生成文件
        run: npm run build

      - name: 5. 发布
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{secrets.npm_token}}
          npm publish
